"""Colour/font themes shared by the PowerPoint renderer and the web preview."""

THEMES = {
    "midnight": {
        "name": "Midnight",
        "bg": "0F172A", "bg2": "1E293B",          # page / card background
        "hero1": "0F172A", "hero2": "1E3A8A",     # gradient for title & section slides
        "text": "E2E8F0", "muted": "94A3B8",
        "accent": "38BDF8", "accent2": "A78BFA",
        "hero_text": "FFFFFF",
        "title_font": "Segoe UI Semibold", "body_font": "Segoe UI",
    },
    "aurora": {
        "name": "Aurora",
        "bg": "FFFFFF", "bg2": "F5F3FF",
        "hero1": "6D28D9", "hero2": "DB2777",
        "text": "1F2937", "muted": "6B7280",
        "accent": "7C3AED", "accent2": "EC4899",
        "hero_text": "FFFFFF",
        "title_font": "Segoe UI Semibold", "body_font": "Segoe UI",
    },
    "sunset": {
        "name": "Sunset",
        "bg": "FFF8F1", "bg2": "FFEDD5",
        "hero1": "C2410C", "hero2": "F59E0B",
        "text": "3B2A20", "muted": "8A6F5E",
        "accent": "EA580C", "accent2": "D97706",
        "hero_text": "FFFFFF",
        "title_font": "Georgia", "body_font": "Segoe UI",
    },
    "forest": {
        "name": "Forest",
        "bg": "F4F7F2", "bg2": "E3EBDD",
        "hero1": "14342B", "hero2": "2F6B4F",
        "text": "1C2B24", "muted": "5D7064",
        "accent": "2F855A", "accent2": "C9A227",
        "hero_text": "F7F3E3",
        "title_font": "Georgia", "body_font": "Calibri",
    },
    "corporate": {
        "name": "Corporate",
        "bg": "FFFFFF", "bg2": "EFF4FA",
        "hero1": "0B3D91", "hero2": "1565C0",
        "text": "1A2433", "muted": "5B6B80",
        "accent": "1565C0", "accent2": "00A3A3",
        "hero_text": "FFFFFF",
        "title_font": "Calibri", "body_font": "Calibri",
    },
    "ocean": {
        "name": "Ocean",
        "bg": "F0F9FF", "bg2": "E0F2FE",
        "hero1": "0C4A6E", "hero2": "0891B2",
        "text": "0C2A3D", "muted": "4B6B80",
        "accent": "0284C7", "accent2": "14B8A6",
        "hero_text": "FFFFFF",
        "title_font": "Segoe UI Semibold", "body_font": "Segoe UI",
    },
    "rose": {
        "name": "Rose",
        "bg": "FFF7F8", "bg2": "FFE4E9",
        "hero1": "9F1239", "hero2": "F43F5E",
        "text": "3F1D26", "muted": "8C5B67",
        "accent": "E11D48", "accent2": "A855F7",
        "hero_text": "FFFFFF",
        "title_font": "Georgia", "body_font": "Segoe UI",
    },
    "mono": {
        "name": "Mono",
        "bg": "FFFFFF", "bg2": "F2F2F2",
        "hero1": "111111", "hero2": "3A3A3A",
        "text": "111111", "muted": "6B6B6B",
        "accent": "111111", "accent2": "8A8A8A",
        "hero_text": "FFFFFF",
        "title_font": "Segoe UI Black", "body_font": "Segoe UI",
    },
    "neon": {
        "name": "Neon",
        "bg": "0A0A12", "bg2": "16162A",
        "hero1": "0A0A12", "hero2": "3B0764",
        "text": "EDEDF7", "muted": "9A9AB8",
        "accent": "22D3EE", "accent2": "F0ABFC",
        "hero_text": "FFFFFF",
        "title_font": "Segoe UI Black", "body_font": "Segoe UI",
    },
    "sand": {
        "name": "Sand",
        "bg": "FAF6EF", "bg2": "EFE6D6",
        "hero1": "5C4632", "hero2": "A47E57",
        "text": "33281D", "muted": "7D6B58",
        "accent": "9C6B3C", "accent2": "4F7A6A",
        "hero_text": "FFF9F0",
        "title_font": "Georgia", "body_font": "Calibri",
    },
    "royal": {
        "name": "Royal",
        "bg": "17112B", "bg2": "251C44",
        "hero1": "1E1440", "hero2": "5B21B6",
        "text": "ECE8F7", "muted": "A69CC8",
        "accent": "FBBF24", "accent2": "C4B5FD",
        "hero_text": "FFFFFF",
        "title_font": "Georgia", "body_font": "Segoe UI",
    },
}

DEFAULT_THEME = "midnight"
